"use client";

import { useState } from "react";
import { Download, FileStack, Loader2, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/loading";
import { Pagination } from "@/components/ui/pagination";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import type { OrganizationReport } from "@/types";

const PAGE_SIZE_OPTIONS = [5, 10, 25, 50];

interface SavedMasterReportsProps {
  reports: OrganizationReport[];
  /** Loads the stored selections back into the builder and opens the preview. */
  onReopen: (report: OrganizationReport) => void;
  onDelete: (report: OrganizationReport) => Promise<void>;
}

/**
 * Master reports that were generated before. They are kept so a period's
 * document can be handed out again months later exactly as it was assembled —
 * including which departments were left out of it.
 */
export function SavedMasterReports({ reports, onReopen, onDelete }: SavedMasterReportsProps) {
  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(5);
  const [busyId, setBusyId] = useState<string | null>(null);

  const totalPages = Math.max(1, Math.ceil(reports.length / pageSize));
  const safePage = Math.min(page, totalPages - 1);
  const rows = reports.slice(safePage * pageSize, (safePage + 1) * pageSize);

  if (reports.length === 0) {
    return (
      <EmptyState
        icon={<FileStack className="h-10 w-10" />}
        title="No organization report generated yet"
        description="Pick a period above, choose the filings to include, and generate the master document."
      />
    );
  }

  const run = async (report: OrganizationReport, action: (r: OrganizationReport) => Promise<void>) => {
    setBusyId(report.id ?? null);
    try {
      await action(report);
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div>
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report</TableHead>
              <TableHead>Period</TableHead>
              <TableHead className="hidden text-center sm:table-cell">Departments</TableHead>
              <TableHead className="hidden text-center sm:table-cell">Left out</TableHead>
              <TableHead className="hidden sm:table-cell">Generated by</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((report) => (
              <TableRow key={report.id}>
                <TableCell className="font-medium text-slate-950">{report.title}</TableCell>
                <TableCell className="capitalize text-slate-600">
                  {report.period} · {report.startDate} to {report.endDate}
                </TableCell>
                <TableCell className="hidden text-center sm:table-cell">{report.sections?.length ?? 0}</TableCell>
                <TableCell className="hidden text-center sm:table-cell">
                  {report.missingDepartments?.length ? (
                    <Badge variant="bg-orange-100 text-orange-700">{report.missingDepartments.length}</Badge>
                  ) : (
                    <span className="text-slate-400">—</span>
                  )}
                </TableCell>
                <TableCell className="hidden text-slate-600 sm:table-cell">{report.generatedByName || "—"}</TableCell>
                <TableCell className="text-right">
                  <div className="inline-flex gap-1">
                    <Button size="sm" variant="outline" onClick={() => onReopen(report)}>
                      <Download className="h-4 w-4" /> Reopen
                    </Button>
                    <Button
                      size="icon"
                      variant="ghost"
                      aria-label={`Delete ${report.title}`}
                      disabled={busyId === report.id}
                      onClick={() => run(report, onDelete)}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <Pagination
        page={safePage}
        totalPages={totalPages}
        totalCount={reports.length}
        hasNext={safePage < totalPages - 1}
        hasPrev={safePage > 0}
        onNext={() => setPage(safePage + 1)}
        onPrev={() => setPage(safePage - 1)}
        pageSize={pageSize}
        pageSizeOptions={PAGE_SIZE_OPTIONS}
        onPageSizeChange={(size) => {
          setPageSize(size);
          setPage(0);
        }}
      />
    </div>
  );
}
